/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Apresentação;

import DomainModel.Cliente;
import DataAccess.ClienteDAO;
import DomainModel.Crediario;
import DataAccess.CrediarioDAO;
import DomainModel.Parcela;
import DataAccess.ParcelaDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author kido
 */

public class JFCrediario extends javax.swing.JFrame {

    /**
     * Creates new form JFCrediario
     */
    List<Cliente> clientes;
    
    public JFCrediario() {
        initComponents();
        formatarData();
        
        clientes = ClienteDAO.getInstance().findAll();
        preencherComboBox();
    }

    public JFCrediario(Crediario c){
        
        initComponents();
        formatarData();
        jRSituacao.setEnabled(true);        
        jCBCliente.setEnabled(false);
        jTFNomeCliente.setEnabled(false);
        
        jTFCrediarioCodigo.setText(String.valueOf(c.getCodigo()));
        jTFValorCrediario.setText(String.valueOf(c.getValor()));
        jTFNomeCliente.setText(c.getCliente().getNome());
        jCBCliente.removeAllItems();
        jCBCliente.addItem(jTFNomeCliente.getText());
        
        formatarData();
        
        DefaultTableModel dtm = (DefaultTableModel) jTCrediario.getModel();
        
        List<Parcela> parcelas = ParcelaDAO.getInstance().findAll();
        for(Parcela p: parcelas){
            if(p.getCrediario().getCodigo() == c.getCodigo()){
                dtm.addRow(new Object[]{p.getDiaUtilBom(),p.getValorParcelado(),p.getSituacao()});
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFNomeCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCBCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTFCrediarioCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFValorCrediario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBAdicionarParcela = new javax.swing.JButton();
        jBRemoverParcela = new javax.swing.JButton();
        jRSituacao = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jFTFDataCrediario = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFValorParcela = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCrediario = new javax.swing.JTable();
        jBAbrirCrediario = new javax.swing.JButton();
        jBPesquisar = new javax.swing.JButton();
        jBTelaPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNomeClienteKeyReleased(evt);
            }
        });

        jLabel4.setText("Cliente");

        jCBCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Nº Crediário");

        jTFCrediarioCodigo.setBackground(new java.awt.Color(108, 251, 103));
        jTFCrediarioCodigo.setEnabled(false);

        jLabel1.setText("Valor do Crediário");

        jLabel5.setText("Data Corrente");

        jBAdicionarParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/add.png"))); // NOI18N
        jBAdicionarParcela.setText("Adicionar Parcela");
        jBAdicionarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarParcelaActionPerformed(evt);
            }
        });

        jBRemoverParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/delete.png"))); // NOI18N
        jBRemoverParcela.setText("Remover Parcela");
        jBRemoverParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverParcelaActionPerformed(evt);
            }
        });

        jRSituacao.setText("Quitado");
        jRSituacao.setEnabled(false);

        jLabel3.setText("Crediário");

        jLabel6.setText("Valor da Parcela");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRSituacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBRemoverParcela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAdicionarParcela))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTFValorCrediario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCrediarioCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFValorParcela))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFDataCrediario))
                            .addComponent(jCBCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFCrediarioCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFTFDataCrediario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFValorCrediario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jTFValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionarParcela)
                    .addComponent(jBRemoverParcela)
                    .addComponent(jRSituacao)
                    .addComponent(jLabel3)))
        );

        jTCrediario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia bom do Mês Seguinte", "Valor da Parcela", "Situação da Parcela"
            }
        ));
        jScrollPane1.setViewportView(jTCrediario);

        jBAbrirCrediario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/tick.png"))); // NOI18N
        jBAbrirCrediario.setText("Registrar");
        jBAbrirCrediario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirCrediarioActionPerformed(evt);
            }
        });

        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/magnifier.png"))); // NOI18N
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/door_in.png"))); // NOI18N
        jBTelaPrincipal.setText("Tela Principal");
        jBTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTelaPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBTelaPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAbrirCrediario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAbrirCrediario)
                    .addComponent(jBPesquisar)
                    .addComponent(jBTelaPrincipal))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formatarData(){
        try{
            MaskFormatter mask = new MaskFormatter("##/##/####");
            mask.install(jFTFDataCrediario);
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(null, "Erro ao Formatar Campo", "ERRO", JOptionPane.ERROR);
        }
    }
    
    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
        
        new JFCrediarioBusca().setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBAbrirCrediarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirCrediarioActionPerformed
        // TODO add your handling code here:
        
        Crediario crediario = new Crediario();
        
        crediario.setValor(Double.parseDouble(jTFValorCrediario.getText()));
        crediario.setSituacao(jRSituacao.isSelected() == true ? "Quitado" : "Não Quitado");
        
        Cliente cliente = null;
        String busca = (String) jCBCliente.getSelectedItem();
        for (Cliente c: clientes){
            if(busca.equals(c.getNome()))
                cliente = c;
        }
        crediario.setCliente(cliente);
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date data = formato.parse(jFTFDataCrediario.getText());
            crediario.setDataDeAbertura(data);
        } catch (ParseException ex) {
            Logger.getLogger(JFCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(jTFCrediarioCodigo.getText().equals("")){
            CrediarioDAO.getInstance().persist(crediario);
            
            int cont = jTCrediario.getRowCount();

            for(int i = 0; i < cont; i++){
                Parcela parcela = new Parcela();
                parcela.setDiaUtilBom((String) jTCrediario.getValueAt(i, 0));
                parcela.setValorParcelado((Double) jTCrediario.getValueAt(i, 1));
                parcela.setSituacao((String) jTCrediario.getValueAt(i, 2));
                parcela.setCrediario(crediario);
                ParcelaDAO.getInstance().persist(parcela);
            }
        }else{           
            crediario.setCodigo(Integer.parseInt(jTFCrediarioCodigo.getText()));
            CrediarioDAO.getInstance().merge(crediario);
            
        }
        
        limpar();
        JOptionPane.showMessageDialog(this, " Crediário registrado com sucesso!");
        
        new JFPagamento(crediario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBAbrirCrediarioActionPerformed
    
    private void jTFNomeClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomeClienteKeyReleased
        // TODO add your handling code here:
        preencherComboBox();
    }//GEN-LAST:event_jTFNomeClienteKeyReleased

    private void jBAdicionarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarParcelaActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel) jTCrediario.getModel();
        
        int cont = 0;
        Double parcela = Double.parseDouble(jTFValorParcela.getText());
        
        for(int i=0; i < cont; i++){
            dtm.setNumRows(0);
        }
        
        dtm.addRow(new Object[]{"informe",parcela,"informe"});
        
    }//GEN-LAST:event_jBAdicionarParcelaActionPerformed

    private void jBRemoverParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverParcelaActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel)jTCrediario.getModel();
        if (jTCrediario.getSelectedRow() >= 0){
            dtm.removeRow(jTCrediario.getSelectedRow());
            jTCrediario.setModel(dtm);
        }else{
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }
    }//GEN-LAST:event_jBRemoverParcelaActionPerformed

    private void jBTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTelaPrincipalActionPerformed
        // TODO add your handling code here:
        
        new JFAutoPecasPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBTelaPrincipalActionPerformed
    
    public void preencherComboBox(){
        jCBCliente.removeAllItems();
        String nome = jTFNomeCliente.getText();
        for(Cliente c: clientes){
            if(c.getNome().toUpperCase().startsWith(nome.toUpperCase()))
            jCBCliente.addItem(c.getNome());
        }
    }
    
    private void limpar(){
        jTFCrediarioCodigo.setText("");
        jTFValorCrediario.setText("");
        jTFValorParcela.setText("");
        DefaultTableModel dtm = (DefaultTableModel) jTCrediario.getModel();
        dtm.setNumRows(0);
    }    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCrediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCrediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCrediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCrediario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCrediario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbrirCrediario;
    private javax.swing.JButton jBAdicionarParcela;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBRemoverParcela;
    private javax.swing.JButton jBTelaPrincipal;
    private javax.swing.JComboBox<String> jCBCliente;
    private javax.swing.JFormattedTextField jFTFDataCrediario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRSituacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCrediario;
    private javax.swing.JTextField jTFCrediarioCodigo;
    private javax.swing.JTextField jTFNomeCliente;
    private javax.swing.JTextField jTFValorCrediario;
    private javax.swing.JTextField jTFValorParcela;
    // End of variables declaration//GEN-END:variables
}
