/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentação;

import DomainModel.Cliente;
import DataAccess.ClienteDAO;
import DomainModel.Pagamento;
import DataAccess.PagamentoDAO;
import DomainModel.Crediario;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kido
 */

public class JFPagamento extends javax.swing.JFrame {

    /**
     * Creates new form JFPagamento
     */
    List<Cliente> clientes;
    Crediario cpg = new Crediario();
    
    public JFPagamento() {
        initComponents();

        clientes = ClienteDAO.getInstance().findAll();
        preencherComboBox();        
    }
    
    public JFPagamento(Crediario crediario) {
        initComponents();
        clientes = ClienteDAO.getInstance().findAll();
        preencherComboBox();
        
        jTFValorPago.setText(String.valueOf(0.0));
        jTFCrediarioValorReceber.setText(String.valueOf(crediario.getValor()));
        
        cpg = crediario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFValorPago = new javax.swing.JTextField();
        jTFNomeCliente = new javax.swing.JTextField();
        jCBCliente = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFCrediarioValorReceber = new javax.swing.JTextField();
        jBEfetuarPagamento = new javax.swing.JButton();
        jBAvista = new javax.swing.JButton();
        jBCrediario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagamento da Venda");

        jLabel1.setText("Valor Pago a Vista");

        jTFValorPago.setEnabled(false);

        jTFNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNomeClienteKeyReleased(evt);
            }
        });

        jCBCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Cliente");

        jLabel5.setText("Valor a Receber");

        jTFCrediarioValorReceber.setEnabled(false);

        jBEfetuarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/tick.png"))); // NOI18N
        jBEfetuarPagamento.setText("Registrar");
        jBEfetuarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEfetuarPagamentoActionPerformed(evt);
            }
        });

        jBAvista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/money.png"))); // NOI18N
        jBAvista.setText("A vista");
        jBAvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAvistaActionPerformed(evt);
            }
        });

        jBCrediario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/note.png"))); // NOI18N
        jBCrediario.setText("Crediário");
        jBCrediario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrediarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCrediarioValorReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEfetuarPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBCrediario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAvista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAvista))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFCrediarioValorReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCrediario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jBEfetuarPagamento)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNomeClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomeClienteKeyReleased
        // TODO add your handling code here:
        preencherComboBox();
    }//GEN-LAST:event_jTFNomeClienteKeyReleased

    private void jBAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAvistaActionPerformed
        // TODO add your handling code here:
        jTFCrediarioValorReceber.setText(String.valueOf(0.0));
        cpg = null;
        Double valor = Double.parseDouble(JOptionPane.showInputDialog(this, "Informe o Valor Pago:"));
        jTFValorPago.setText(String.valueOf(valor));
    }//GEN-LAST:event_jBAvistaActionPerformed

    private void jBCrediarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrediarioActionPerformed
        // TODO add your handling code here:
        new JFCrediario().setVisible(true);
        this.dispose();
        jTFValorPago.setText(String.valueOf(0.0));
    }//GEN-LAST:event_jBCrediarioActionPerformed

    private void jBEfetuarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEfetuarPagamentoActionPerformed
        // TODO add your handling code here:
        Pagamento pagamento = new Pagamento();
        
        pagamento.setValorPago(Double.parseDouble(jTFValorPago.getText()));
        pagamento.setValorReceber(Double.parseDouble(jTFCrediarioValorReceber.getText()));
        pagamento.setCrediario(cpg);
        Cliente cliente = null;
        String busca = (String) jCBCliente.getSelectedItem();
        for (Cliente c: clientes){
            if(busca.equals(c.getNome()))
                cliente = c;
        }
        pagamento.setCliente(cliente);
        
        PagamentoDAO.getInstance().persist(pagamento);

        limpar();
        JOptionPane.showMessageDialog(this, " Pagamento realizado com sucesso!");
        this.dispose();
    }//GEN-LAST:event_jBEfetuarPagamentoActionPerformed

    public void preencherComboBox(){
        jCBCliente.removeAllItems();
        String nome = jTFNomeCliente.getText();
        for(Cliente c: clientes){
            if(c.getNome().toUpperCase().startsWith(nome.toUpperCase()))
            jCBCliente.addItem(c.getNome());
        }
    }
    
    private void limpar(){
        jTFCrediarioValorReceber.setText("");
        jTFNomeCliente.setText("");
        jTFValorPago.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAvista;
    private javax.swing.JButton jBCrediario;
    private javax.swing.JButton jBEfetuarPagamento;
    private javax.swing.JComboBox<String> jCBCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFCrediarioValorReceber;
    private javax.swing.JTextField jTFNomeCliente;
    private javax.swing.JTextField jTFValorPago;
    // End of variables declaration//GEN-END:variables
}
