/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Apresentação;

import DomainModel.Mercadoria;
import DataAccess.MercadoriaDAO;
import DomainModel.Vendas;
import DataAccess.VendasDAO;
import DomainModel.ItemVenda;
import DataAccess.ItemVendaDAO;
import DomainModel.Pagamento;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kido
 */

public class JFVendas extends javax.swing.JFrame {

    /**
     * Creates new form JFVendas
     */
    
    List<Mercadoria> mercadorias;
    Pagamento vpg = new Pagamento();
    
    public JFVendas() {
        initComponents();
        formatarData();
        
        mercadorias = MercadoriaDAO.getInstance().findAll();
        
        preencherComboBox();
    }
    
    public JFVendas(Vendas c){
        
        initComponents();
        jRSituacao.setEnabled(true);
        
        jTFVendaCodigo.setText(String.valueOf(c.getCodigo()));
        jTFValorTotal.setText(String.valueOf(c.getValorTotal()));
                
        formatarData();
        
        mercadorias = MercadoriaDAO.getInstance().findAll();
        
        preencherComboBox();
        
        DefaultTableModel dtm = (DefaultTableModel) jTVendas.getModel();
        
        List<ItemVenda> itensVenda = ItemVendaDAO.getInstance().findAll();
        for(ItemVenda i: itensVenda){
            if(i.getVendas().getCodigo() == c.getCodigo()){
                dtm.addRow(new Object[]{i.getMercadoria().getCodigo(),i.getMercadoria().getDescricao(),i.getMercadoria().getValorUnitario(),i.getQuantidade(),i.getQuantidade() * i.getMercadoria().getValorUnitario()});
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jBAdicionarItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTFVendaCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFValorTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCBMercadoria = new javax.swing.JComboBox<>();
        jTFDescricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFTFDataVenda = new javax.swing.JFormattedTextField();
        jBRemoverItem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jRSituacao = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVendas = new javax.swing.JTable();
        jBFinalizarVendas = new javax.swing.JButton();
        jBTelaPrincipal = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jBPagamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Vendas - Realizar Vendas");

        jLabel3.setText("Quantidade");

        jBAdicionarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/add.png"))); // NOI18N
        jBAdicionarItem.setText("Adicionar");
        jBAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarItemActionPerformed(evt);
            }
        });

        jLabel2.setText("Nº Venda");

        jTFVendaCodigo.setBackground(new java.awt.Color(108, 251, 103));
        jTFVendaCodigo.setEnabled(false);

        jLabel4.setText("Total R$");

        jTFValorTotal.setEnabled(false);

        jLabel5.setText("Mercadoria");

        jLabel1.setText("Data");

        jCBMercadoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTFDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFDescricaoKeyReleased(evt);
            }
        });

        jLabel6.setText("Descrição");

        jFTFDataVenda.setToolTipText("");

        jBRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/delete.png"))); // NOI18N
        jBRemoverItem.setText("Remover");
        jBRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverItemActionPerformed(evt);
            }
        });

        jLabel7.setText("Situação");

        jRSituacao.setText("Cancelada");
        jRSituacao.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFVendaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(254, 254, 254)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFDataVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jTFQuantidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCBMercadoria, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRSituacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBRemoverItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAdicionarItem)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFVendaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jFTFDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCBMercadoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionarItem)
                    .addComponent(jBRemoverItem)
                    .addComponent(jLabel7)
                    .addComponent(jRSituacao))
                .addContainerGap())
        );

        jTVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mercadoria", "Valor Unitário", "Quantidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTVendas);

        jBFinalizarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/tick.png"))); // NOI18N
        jBFinalizarVendas.setText("Finalizar");
        jBFinalizarVendas.setEnabled(false);
        jBFinalizarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarVendasActionPerformed(evt);
            }
        });

        jBTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/door_in.png"))); // NOI18N
        jBTelaPrincipal.setText("Tela Principal");
        jBTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTelaPrincipalActionPerformed(evt);
            }
        });

        jBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/magnifier.png"))); // NOI18N
        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jBPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icones/money.png"))); // NOI18N
        jBPagamento.setText("Pagamento");
        jBPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBTelaPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFinalizarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBFinalizarVendas)
                    .addComponent(jBTelaPrincipal)
                    .addComponent(jBuscar)
                    .addComponent(jBPagamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTelaPrincipalActionPerformed
        // TODO add your handling code here:
        new JFAutoPecasPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBTelaPrincipalActionPerformed

    private void somarValorTotal(){
        
        Double valor, soma = 0.0;
        
        int cont = jTVendas.getRowCount();
        
        for(int i = 0; i < cont; i++){
            valor = (Double) jTVendas.getValueAt(i, 4);
            soma += valor;
        }
        
        jTFValorTotal.setText(String.valueOf(soma));
    }
    
    private void jBAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarItemActionPerformed
        // TODO add your handling code here:
        Mercadoria mercadoria = null;
        String busca = (String) jCBMercadoria.getSelectedItem();
        for (Mercadoria m: mercadorias){
            if(busca.equals(m.getDescricao()))
                mercadoria = m;
        }
        
        DefaultTableModel dtm = (DefaultTableModel) jTVendas.getModel();
        
        int cont = 0;
        Double quantidade = 0.0;
        quantidade = Double.parseDouble(jTFQuantidade.getText());
        int qtd = Integer.parseInt(jTFQuantidade.getText());
        
        for(int i=0; i < cont; i++){
            dtm.setNumRows(0);
        }
        
        dtm.addRow(new Object[]{mercadoria.getCodigo(),mercadoria.getDescricao(),mercadoria.getValorUnitario(),qtd,quantidade * mercadoria.getValorUnitario()});
        
        somarValorTotal();
    }//GEN-LAST:event_jBAdicionarItemActionPerformed

    private void jTFDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescricaoKeyReleased
        // TODO add your handling code here:
        preencherComboBox();
    }//GEN-LAST:event_jTFDescricaoKeyReleased

    private void formatarData(){
        try{
            MaskFormatter mask = new MaskFormatter("##/##/####");
            mask.install(jFTFDataVenda);
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(null, "Erro ao Formatar Campo", "ERRO", JOptionPane.ERROR);
        }
    }
    
    private void jBFinalizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarVendasActionPerformed
        // TODO add your handling code here:
        
        Vendas vendas = new Vendas();
        ItemVenda itemVenda = new ItemVenda();
        
        vendas.setValorTotal(Double.parseDouble(jTFValorTotal.getText()));
        vendas.setSituacao(jRSituacao.isSelected() == true ? "Cancelada" : "Confirmada");
                
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date data = formato.parse(jFTFDataVenda.getText());
            vendas.setDataDeVenda(data);
        } catch (ParseException ex) {
            Logger.getLogger(JFCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(jTFVendaCodigo.getText().equals("")){
            VendasDAO.getInstance().persist(vendas);
            
                    int cont = jTVendas.getRowCount();
                    Mercadoria mercadoria = new Mercadoria(); 

                    for(int i = 0; i < cont; i++){
                        itemVenda = new ItemVenda();
                        mercadoria = new Mercadoria();
                        mercadoria = MercadoriaDAO.getInstance().getById((int) jTVendas.getValueAt(i, 0));
                        itemVenda.setMercadoria(mercadoria);
                        itemVenda.setVendas(vendas);
                        itemVenda.setQuantidade((int) jTVendas.getValueAt(i, 3));
                        ItemVendaDAO.getInstance().persist(itemVenda);
                    }
        }else{           
            vendas.setCodigo(Integer.parseInt(jTFVendaCodigo.getText()));
            VendasDAO.getInstance().merge(vendas);
        }
        
        limpar();
        JOptionPane.showMessageDialog(this, " Venda realizada com sucesso!");
        
    }//GEN-LAST:event_jBFinalizarVendasActionPerformed

    private void jBRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverItemActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel)jTVendas.getModel();
        if (jTVendas.getSelectedRow() >= 0){
            dtm.removeRow(jTVendas.getSelectedRow());
            jTVendas.setModel(dtm);
        }else{
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }
        
        somarValorTotal();
    }//GEN-LAST:event_jBRemoverItemActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // TODO add your handling code here:

        new JFVendasBusca().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jBPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPagamentoActionPerformed
        // TODO add your handling code here:
        
        new JFPagamento().setVisible(true);
        jBFinalizarVendas.setEnabled(true);
    }//GEN-LAST:event_jBPagamentoActionPerformed
    
    public void preencherComboBox(){
        jCBMercadoria.removeAllItems();
        String descricao = jTFDescricao.getText();
        for(Mercadoria m: mercadorias){
            if(m.getDescricao().toUpperCase().startsWith(descricao.toUpperCase()))
            jCBMercadoria.addItem(m.getDescricao());
        }
    }
    
    private void limpar(){
        jTFVendaCodigo.setText("");
        jTFDescricao.setText("");
        jTFQuantidade.setText("");
        jTFValorTotal.setText("");
        DefaultTableModel dtm = (DefaultTableModel) jTVendas.getModel();
        dtm.setNumRows(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarItem;
    private javax.swing.JButton jBFinalizarVendas;
    private javax.swing.JButton jBPagamento;
    private javax.swing.JButton jBRemoverItem;
    private javax.swing.JButton jBTelaPrincipal;
    private javax.swing.JButton jBuscar;
    private javax.swing.JComboBox<String> jCBMercadoria;
    private javax.swing.JFormattedTextField jFTFDataVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRSituacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTextField jTFQuantidade;
    private javax.swing.JTextField jTFValorTotal;
    private javax.swing.JTextField jTFVendaCodigo;
    private javax.swing.JTable jTVendas;
    // End of variables declaration//GEN-END:variables

}
